export default {
  login: 'Sign in',
  register: 'Signup',
  emailPlaceholder: 'Email Address',
  passwordPlaceholder: 'Password',
  registerText: `Don't have an account?`,
  loginText: 'Already have an account ?',
  confirmPasswordPlaceholder: 'Confirm Password',
  userName: 'UserName',
  loginSuccess: 'Login Success',
  registerSuccess: 'Register Sucsess',
  SomethingWrong: 'Something Wrong',
  TryAgain: 'Try Again',
  Hello: 'Hello',
  Comma: ',',
  ClickFavourites: 'Click your favourites here',
  Dashboard: 'Dashboard',
  Map: 'Map',
  Booking: 'Booking',
  Setting: 'Setting',
  Description: 'Description',
  Bookings: 'Booking',
  Confirm: 'CONFIRM',
  FillInformation: 'Please fill information',
  Name: 'Name....',
  PhNo: 'Ph No....',
  PickDate: 'Pick Date....',
  Edit: 'Edit',
  Delete: 'Delete',
  BookingSuccess: 'Booking Successful',
  UpdateSuccess: 'Update Successful',
  DeleteSuccess: 'Delete Successful',
  NoBooking: 'No Booking, yet.',
  NoBookingList: "You don't have any booking list.",
  LogoutSuccess: 'logout successful',
  Logout: 'Logout',
  ClickFav: 'View to your favourites',
  Favourites: 'Favourites',
  YourFavourite: 'Your Favourite Restaurants',
  BookTable: 'Book a table',
  UhOh: "Uh-oh! You don't have any",
  Yet: 'favourites yet.',
  Click: 'Click the ♡ to add your favourites',
  BrowseNow: 'ရှာဖွေရန်',
};
