export default {
  login: 'အကောင့်ဝင်ပါ',
  register: 'အကောင့်အသစ်ဖွင့်ပါ',
  emailPlaceholder: 'အီးမေးလ်',
  passwordPlaceholder: 'လျှို့ဝှက်နံပတ်',
  registerText: 'အကောင့်မရှိသေးပါဘူးလား ?',
  loginText: 'အကောင့်တစ်ခုရှိပြီးသားပါလား ?',
  confirmPasswordPlaceholder: 'ထပ်မံအတည်ပြုပါ',
  userName: 'အမည်',
  loginSuccess: 'အကောင့်ဝင်ခြင်းအောင်မြင်ပါသည်',
  registerSuccess: 'အကောင့်အသစ်ဖွင့်ခြင်းအောင်မြင်ပါသည်',
  SomethingWrong: 'တစ်ခုခုမှားယွင်းနေပါသည်',
  TryAgain: 'ထပ်မံကြိုးစားပါ',
  Hello: 'မင်္ဂလာပါ',
  Comma: '၊',
  ClickFavourites: 'သင့်စိတ်ကြိုက်ဆိုင် များ ကိုကြည့်ရန်',
  Dashboard: 'ဆိုင်များ',
  Map: 'မြေပုံ',
  Booking: 'ဘွတ်ကင်',
  Setting: 'ဆက်တင်',
  Description: 'ဖော်ပြချက်',
  Bookings: 'ကြိုတင်စာရင်းပေးရန်',
  Confirm: 'အတည်ပြုပါ',
  FillInformation: 'အချက်အလက် များဖြည့်ပါ',
  Name: 'အမည်....',
  PhNo: 'ဖုန်းနံပါတ်....',
  PickDate: 'ရက်စွဲရွေးရန်....',
  Edit: 'ပြင်ဆင်ရန်',
  Delete: 'ပယ်ဖျက်ရန်',
  Confrim: 'အတည်ပြုသည်',
  BookingSuccess: 'ကြိုတင်စာရင်းပေးခြင်းအောင်မြင်ပါသည်',
  UpdateSuccess: 'ပြင်ဆင်ပြီးပါပြီ',
  DeleteSuccess: 'ဖျက်ပြီးပါပြီ',
  NoBooking: 'မရှိသေးပါ ။',
  NoBookingList: 'ကြိုတင်စာရင်းပေးထားခြင်း မပြုလုပ်ရသေးပါ ။',
  LogoutSuccess: 'အကောင့်ထွက်ပြီးပါပြီ',
  Logout: 'ထွက်ရန်',
  ClickFav: 'သင့်စိတ်ကြိုက်ဆိုင် များ ကိုကြည့်ရန်',
  Favourites: 'စိတ်ကြိုက်ဆိုင်များ',
  YourFavourite: 'သင့်စိတ်ကြိုက်ဆိုင် များ',
  BookTable: 'ကြိုတင်စာရင်းသွင်းရန်',
  UhOh: 'စိတ်ကြိုက်ရွေးချယ်ထားသော ',
  Yet: 'စာရင်းမရှိသေးပါ ။',
  Click: 'စိတ်ကြိုက်စာရင်းထဲထည့်ရန်  ♡ ကို နှိပ်ပါ',
  BrowseNow: 'ရှာဖွေရန်',
};
